---
- name: Configure executor
  hosts: localhost
  vars_files: main.yml
  roles:
    - { role: configure-executor }
- name: Configure OCNE Nodes
  hosts: ocne-nodes
  vars_files: main.yml
  roles:
    - { role: configure-nodes }